# Generated by Django 4.2.16 on 2025-02-08 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book_tracker', '0003_book_google_books_id_alter_book_author_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
