# Generated by Django 4.2.16 on 2025-02-17 23:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_tracker', '0007_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='genres',
        ),
        migrations.DeleteModel(
            name='Genre',
        ),
    ]
