# Generated by Django 4.2.16 on 2025-02-11 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inbox', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inbox',
            old_name='body',
            new_name='message',
        ),
        migrations.AlterField(
            model_name='inbox',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
